from typing import IO, Any, Protocol
from uuid import UUID


class IntegrationsStore(Protocol):
    async def add_upload(self, u: dict[str, Any]) -> None: ...
    async def get_upload(self, upload_id: UUID) -> dict[str, Any] | None: ...
    async def add_source(self, s: dict[str, Any]) -> None: ...
    async def get_source(self, source_id: UUID) -> dict[str, Any] | None: ...
    async def list_sources(self) -> list[dict[str, Any]]: ...
    async def update_source(self, source_id: UUID, **values: Any) -> None: ...
    async def next_mapping_version(self, source_id: UUID) -> int: ...
    async def add_mapping(self, m: dict[str, Any]) -> None: ...
    async def set_mapping_status(self, source_id: UUID, version: int, status: str,
                                 error: str | None) -> None: ...
    async def add_sync_run(self, run: dict[str, Any]) -> None: ...
    async def finish_sync_run(self, run_id: UUID, status: str, result: dict[str, Any]) -> None: ...


class FileStore(Protocol):
    async def put(self, key: str, source: IO[bytes], *, max_bytes: int,
                  content_type: str) -> dict[str, Any]:
        """Obyekt reference’i: {bucket, key, checksum_sha256, size_bytes}."""
        ...


class Outbox(Protocol):
    async def publish(self, event_type: str, payload: dict[str, Any], *, aggregate_id: UUID,
                      aggregate_version: int) -> None: ...
