from decimal import Decimal
from typing import Protocol
from uuid import UUID

from ..domain.budget import BudgetLimits, BudgetUsage


class BudgetStore(Protocol):
    async def lock(self) -> None:
        """Tenant budjeti bo‘yicha ketma-ketlik (parallel rezervlar limitni aylanib o‘tmasin)."""
        ...

    async def limits(self) -> BudgetLimits | None: ...
    async def set_limits(self, limits: BudgetLimits, *, user_id: UUID) -> None: ...
    async def usage(self, timezone: str) -> BudgetUsage: ...
    async def reserve(self, task_id: UUID, reservation_id: UUID, amount: Decimal) -> bool:
        """Takroriy chaqiruvda False (idempotent)."""
        ...

    async def settle(self, task_id: UUID, actual: Decimal, input_tokens: int,
                     output_tokens: int) -> None: ...
    async def release(self, task_id: UUID) -> None: ...
