from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from ..domain.model import (
    AuthSession,
    Email,
    Invitation,
    Membership,
    PasswordResetToken,
    Tenant,
    User,
)


class UserRepository(Protocol):
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_many(self, user_ids: list[UUID]) -> list[User]: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...


class TenantRepository(Protocol):
    async def add(self, tenant: Tenant) -> None: ...
    async def list_by_ids(self, tenant_ids: list[UUID]) -> list[Tenant]: ...


class MembershipRepository(Protocol):
    async def add(self, membership: Membership) -> None: ...
    async def get(self, tenant_id: UUID, user_id: UUID) -> Membership | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Membership]: ...
    async def list_for_tenant(self, tenant_id: UUID) -> list[Membership]: ...
    async def count_owners(self, tenant_id: UUID) -> int: ...
    async def save(self, membership: Membership) -> None: ...
    async def delete(self, membership_id: UUID) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: AuthSession) -> None: ...
    async def get_by_id(self, session_id: UUID) -> AuthSession | None: ...
    async def get_by_token_hash(self, token_hash: str) -> AuthSession | None: ...
    async def save(self, session: AuthSession) -> None: ...
    async def delete(self, session_id: UUID) -> None: ...
    async def delete_for_user(self, user_id: UUID) -> None: ...


class InvitationRepository(Protocol):
    async def add(self, invitation: Invitation) -> None: ...
    async def get_by_token_hash(self, token_hash: str) -> Invitation | None: ...
    async def list_pending(self, tenant_id: UUID) -> list[Invitation]: ...
    async def save(self, invitation: Invitation) -> None: ...


class PasswordResetRepository(Protocol):
    async def add(self, token: PasswordResetToken) -> None: ...
    async def get_by_token_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def save(self, token: PasswordResetToken) -> None: ...


class IdentityUnitOfWork(Protocol):
    """Bitta lokal DB tranzaksiyasi. Commit qilinmasa chiqishda rollback."""

    @property
    def users(self) -> UserRepository: ...
    @property
    def tenants(self) -> TenantRepository: ...
    @property
    def memberships(self) -> MembershipRepository: ...
    @property
    def sessions(self) -> SessionRepository: ...
    @property
    def invitations(self) -> InvitationRepository: ...
    @property
    def password_resets(self) -> PasswordResetRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

    async def bind(
        self,
        *,
        tenant_id: UUID | None,
        user_id: UUID | None,
        invitation_token_hash: str | None = None,
    ) -> None:
        """Tranzaksiya ichida RLS kontekstini o‘rnatadi.

        `invitation_token_hash` faqat taklifni qabul qilishda, tenant hali ma’lum
        bo‘lmaganda aynan shu taklif satrini ko‘rish uchun beriladi.
        """
        ...

    async def commit(self) -> None: ...


class IdentityUnitOfWorkFactory(Protocol):
    def __call__(self) -> IdentityUnitOfWork: ...
