from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from ..domain.model import AuthSession, Email, Membership, Tenant, User


class UserRepository(Protocol):
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...


class TenantRepository(Protocol):
    async def add(self, tenant: Tenant) -> None: ...
    async def list_by_ids(self, tenant_ids: list[UUID]) -> list[Tenant]: ...


class MembershipRepository(Protocol):
    async def add(self, membership: Membership) -> None: ...
    async def get(self, tenant_id: UUID, user_id: UUID) -> Membership | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Membership]: ...


class SessionRepository(Protocol):
    async def add(self, session: AuthSession) -> None: ...
    async def get_by_id(self, session_id: UUID) -> AuthSession | None: ...
    async def get_by_token_hash(self, token_hash: str) -> AuthSession | None: ...
    async def save(self, session: AuthSession) -> None: ...
    async def delete(self, session_id: UUID) -> None: ...


class IdentityUnitOfWork(Protocol):
    """Bitta lokal DB tranzaksiyasi. Commit qilinmasa chiqishda rollback."""

    @property
    def users(self) -> UserRepository: ...
    @property
    def tenants(self) -> TenantRepository: ...
    @property
    def memberships(self) -> MembershipRepository: ...
    @property
    def sessions(self) -> SessionRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

    async def bind(self, *, tenant_id: UUID | None, user_id: UUID | None) -> None:
        """Tranzaksiya ichida tenant/foydalanuvchi kontekstini o‘rnatadi (RLS uchun)."""
        ...

    async def commit(self) -> None: ...


class IdentityUnitOfWorkFactory(Protocol):
    def __call__(self) -> IdentityUnitOfWork: ...
