from datetime import datetime
from typing import Protocol


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...


class TotpService(Protocol):
    def new_secret(self) -> str: ...
    def verify(self, secret: str, code: str, now: datetime) -> bool: ...
    def provisioning_uri(self, secret: str, account: str) -> str: ...


class SecretBox(Protocol):
    """Saqlanadigan maxfiy qiymatlarni (masalan, TOTP secret) shifrlash."""

    def encrypt(self, plaintext: str) -> str: ...
    def decrypt(self, ciphertext: str) -> str: ...


class SessionTokens(Protocol):
    def new_token(self) -> str: ...
    def hash(self, token: str) -> str: ...
